
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: pwd
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: ls -al
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: ls -al
  workingDirectory: $(System.DefaultWorkingDirectory)/src

- script: ls -al
  workingDirectory: '$(System.DefaultWorkingDirectory)/src'

- script: ls -al
  workingDirectory: "$(System.DefaultWorkingDirectory)/src"

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    #workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    projects: src/CompanyName.MyMeetings.sln

- task: DotNetCoreCLI@2
  inputs:
    command: build
    workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    projects: ./CompanyName.MyMeetings.sln
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    projects: 'CompanyName.MyMeetings.sln'
    #arguments: '--configuration $(buildConfiguration)'
  #displayName: 'dotnet test $(buildConfiguration)'
