
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  MeetingsConnectionString: "test-conn"

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: src/CompanyName.MyMeetings.sln
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: src/CompanyName.MyMeetings.sln
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: src/CompanyName.MyMeetings.sln
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet test $(buildConfiguration)'
