
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:

- job: backend
  steps:

  - task: Cache@2
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
      path: $(NUGET_PACKAGES)
    displayName: cache nuget
  
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: src/CompanyName.MyMeetings.sln
      arguments: --locked-mode
    displayName: 'dotnet restore'

  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: src/CompanyName.MyMeetings.sln
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: src/CompanyName.MyMeetings.sln
      arguments: '--configuration $(buildConfiguration)'
    env:
      MeetingsConnectionString: "Server=localhost;Database=MyMeetings;User Id=sa;Password=test;"
    displayName: 'dotnet test $(buildConfiguration)'

- job: frontend
  steps:

  - task: Cache@2
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
      path: $(NUGET_PACKAGES)
    displayName: cache nuget

  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      arguments: --locked-mode
      projects: src/CompanyName.MyMeetings.sln
    displayName: 'dotnet restore'
  
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | src/Web/yarn.lock'
      path: src/Web/node_modules
    displayName: cache node_modules
  
  - task: Bash@3
    inputs:
      targetType: inline
      workingDirectory: src/Web
      script: yarn --frozen-lockfile
    displayName: yarn install
  
  - task: Bash@3
    inputs:
      targetType: inline
      workingDirectory: src/Web
      script: yarn build
    displayName: yarn build

  - task: Bash@3
    inputs:
      targetType: inline
      workingDirectory: src/Web
      script: yarn test:unit
    displayName: yarn test
