
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    projects: '*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    projects: '*.sln'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    projects: '*.sln'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet test $(buildConfiguration)'
